### ISSUE TITLE
PHP 5.6 support?

### ISSUE THREAD

**Issue by philipabbey** [ethanhann/rejson-php#1]
I was interested to discover your project here, only I'm working on a NAS which is stuck on an old PHP version. I've decided not to update the NAS manually as there are several bits of the installation that look non-standard.

```
PHP 5.6.33-0+deb8u1.netgear1 (cli) (built: Jan 22 2018 23:23:07)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```

How much of the code relies on v7 of PHP? Is there any chance that this prerequisite condition can be lowered?

Many thanks,

Philip

**Comment by ethanhann** [comment]
I think all you would need to do is strip out the argument and return type hints to make it work with PHP 5.6.
